Fix PowerMock classloader issue in IfTttDaemonTest
  [ERROR] ifTttDaemonTest(org.opennms.features.ifttt.IfTttDaemonTest)  Time elapsed: 3.085 s  <<< ERROR!
  org.springframework.dao.DataAccessResourceFailureException: Failed reloading data for object 'null' from file '/home/circleci/project/features/ifttt/src/test/resources/etc/ifttt-config.xml'. Unexpected Throwable received while issuing reload.; nested exception is java.lang.IllegalAccessError: class javax.xml.validation.SchemaFactory (in unnamed module @0x6f044c58) cannot access class jdk.xml.internal.SecuritySupport (in module java.xml) because module java.xml does not export jdk.xml.internal to unnamed module @0x6f044c58
          at org.opennms.features.ifttt.IfTttDaemonTest.runIfTttDaemonTest(IfTttDaemonTest.java:251)
          at org.opennms.features.ifttt.IfTttDaemonTest.ifTttDaemonTest(IfTttDaemonTest.java:194)
  Caused by: java.lang.IllegalAccessError: class javax.xml.validation.SchemaFactory (in unnamed module @0x6f044c58) cannot access class jdk.xml.internal.SecuritySupport (in module java.xml) because module java.xml does not export jdk.xml.internal to unnamed module @0x6f044c58
          at org.opennms.features.ifttt.IfTttDaemonTest.runIfTttDaemonTest(IfTttDaemonTest.java:251)
          at org.opennms.features.ifttt.IfTttDaemonTest.ifTttDaemonTest(IfTttDaemonTest.java:194)

* https://github.com/powermock/powermock/issues/864